credentials:
  usernames:
    zeke:
      name: Zeked
      email: zeke@example.com
      password: $2b$12$5oAbJ8IF5BQfXjtqFdw3NOhW6/IRszOc3X7NB.Ir8F7QcNB//qnF2
cookie:
  name: my_app_cookie
  key: super_secret_key_123
  expiry_days: 1
preauthorized:
  emails:
    - admin@example.com
